name: Release Workflow

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
            target: x86_64-unknown-linux-musl
            binary: rust-release-automation-test
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            binary: rust-release-automation-test.exe

    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        run: |
          rustup default stable
          rustup update
          rustup target add ${{ matrix.target }}
      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}
      - name: zip-linux
        if: matrix.os == 'linux'
        run: |
          cd target/${{ matrix.target }}/release/
          zip rrat-${{ matrix.os }}-${{ github.ref_name }}.zip ${{ matrix.binary }}
      - name: zip-windows
        if: matrix.os == 'windows'
        run: |
          cd target/${{ matrix.target }}/release/
          compress-archive -Path ${{ matrix.binary }} -DestinationPath rrat-${{ matrix.os }}-${{ github.ref_name }}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-zip
          path: target/${{ matrix.target }}/release/rrat-${{ matrix.os }}-${{ github.ref_name }}.zip

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name:
          merge-multiple: true
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref }}
          name: Version ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
          artifacts: "*.zip"

